version: '3.2'
services:
  es01:
    image: elasticsearch:7.6.1
    container_name: es01
    environment:
      - network.publish_host={es01_HOST_IP}
      - node.name=es01
      - cluster.name=es-docker-cluster
      - discovery.seed_hosts={es02_HOST_IP},{es03_HOST_IP}
      - node.master=true
      - node.data=true
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms8g -Xmx8g"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - type: volume
        source: esdata
        target: /usr/share/elasticsearch/data
    ports:
      - 9200:9200
      - 9300:9300
  es02:
    image: elasticsearch:7.6.1
    container_name: es02
    environment:
      - network.publish_host={es02_HOST_IP}
      - node.name=es02
      - cluster.name=es-docker-cluster
      - discovery.seed_hosts={es01_HOST_IP},{es03_HOST_IP}
      - node.master=true
      - node.data=true
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms8g -Xmx8g"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - type: volume
        source: esdata
        target: /usr/share/elasticsearch/data
    ports:
      - 9200:9200
      - 9300:9300
  es03:
    image: elasticsearch:7.6.1
    container_name: es03
    environment:
      - network.publish_host={es03_HOST_IP}
      - node.name=es03
      - cluster.name=es-docker-cluster
      - discovery.seed_hosts={es01_HOST_IP},{es02_HOST_IP}
      - node.master=true
      - node.data=true
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms8g -Xmx8g"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - type: volume
        source: esdata
        target: /usr/share/elasticsearch/data
    ports:
      - 9200:9200
      - 9300:9300
  kib01:
    image: docker.elastic.co/kibana/kibana:7.7.1
    container_name: kib01
    ports:
      - 5601:5601
    environment:
      ELASTICSEARCH_URL: http://es01:9200
      ELASTICSEARCH_HOSTS: http://es01:9200
volumes:
  esdata: